name = "matri"
compatibility_date = "2024-09-23"
main = "./src/worker.js"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"
binding = "ASSETS"
run_worker_first = true

[[d1_databases]]
binding = "DB"
database_name = "matri-db"
database_id = "ccc687b0-4397-4a16-9795-04a0ad162a8c"
